In [13]:
import nltk
from nltk.corpus import brown
nltk.download('brown')

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\hhars\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\brown.zip.


True

In [24]:
# Get categories (genres) in the Brown Corpus
categories = brown.categories()
for c in categories:
    print(c, end=" ")
    print(len(brown.words(categories=c)))


adventure 69342
belles_lettres 173096
editorial 61604
fiction 68488
government 70117
hobbies 82345
humor 21695
learned 181888
lore 110299
mystery 57169
news 100554
religion 39399
reviews 40704
romance 70022
science_fiction 14470


In [25]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [28]:
>>> nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hhars\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [54]:

document = """In the quiet town nestled between rolling hills and meandering streams, life unfolded at a leisurely pace. The cobblestone streets led to charming cafes where locals gathered to share stories over cups of steaming coffee. Towering oak trees shaded the parks, their leaves rustling in the gentle breeze. 
"""
sentence = " It was a place where $ 40,000 $40,000 time seemed 1,2,3 23.23.32.233 to slow."

In [75]:
sents = sent_tokenize(document)
sents

['In the quiet town nestled between rolling hills and meandering streams, life unfolded at a leisurely pace.',
 'The cobblestone streets led to charming cafes where locals gathered to share stories over cups of steaming coffee.',
 'Towering oak trees shaded the parks, their leaves rustling in the gentle breeze.']

In [76]:
words = word_tokenize(sentence)
words

['It',
 'was',
 'a',
 'place',
 'where',
 '$',
 '40,000',
 '$',
 '40,000',
 'time',
 'seemed',
 '1,2,3',
 '23.23.32.233',
 'to',
 'slow',
 '.']

In [77]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hhars\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [161]:
from nltk.corpus import stopwords

In [162]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [163]:
def stopword_removal(text, stop_words):
    useful_words = [w for w in text if w not in stop_words or w == 'not']
    return useful_words

In [164]:
words = 'I am not very much bothered about her.'.split()
x = stopword_removal(words, stop_words)
x

['I', 'not', 'much', 'bothered', 'her.']

In [165]:
text = 'It was a place where time seemed to slow hharshit8118@gmail.com your marks are 59.34 and cost is $12,223 contact@sub1.sub2.example.org h@.d jane_doe@example.org user123@example.net mary-jane@example.co info@sub.example.com john.doe@example.com'
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer('[a-z.0-9_-]+@[a-z0-9._]+\.[a-z]+')
emails = tokenizer.tokenize(text)
emails

['hharshit8118@gmail.com',
 'contact@sub1.sub2.example.org',
 'jane_doe@example.org',
 'user123@example.net',
 'mary-jane@example.co',
 'info@sub.example.com',
 'john.doe@example.com']

In [166]:
from nltk.stem.lancaster import LancasterStemmer
from nltk.stem.snowball import SnowballStemmer, PorterStemmer

In [167]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hhars\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [168]:
ps = PorterStemmer()
ss = SnowballStemmer('english')
ls = LancasterStemmer()

In [169]:
listArr = ["jumping", "jumps", "jumped", "jump", "Programming", "program", "programs", "Programmes"]
for w in listArr:
    print(f'porter {w} - {ps.stem(w)}')
    print(f'snowball {w} - {ss.stem(w)}')
    print(f'lancaster {w} - {ls.stem(w)}')

porter jumping - jump
snowball jumping - jump
lancaster jumping - jump
porter jumps - jump
snowball jumps - jump
lancaster jumps - jump
porter jumped - jump
snowball jumped - jump
lancaster jumped - jump
porter jump - jump
snowball jump - jump
lancaster jump - jump
porter Programming - program
snowball Programming - program
lancaster Programming - program
porter program - program
snowball program - program
lancaster program - program
porter programs - program
snowball programs - program
lancaster programs - program
porter Programmes - programm
snowball Programmes - programm
lancaster Programmes - program


In [170]:
corpus = [
    "Within the confines of a sunlit studio, an artist's creative spirit comes to life. The room is adorned with vibrant canvases, each telling a unique story born from the depths of imagination. Brushes dance across palettes, blending colors with purpose and passion. The scent of oil paint lingers in the air, a testament to the artist's dedication to the craft. The studio is a sanctuary where ideas flow freely, and every stroke on canvas is a manifestation of an inspired journey, inviting observers to glimpse into the soul of the artist and the world that unfolds within the realm of creativity.",
    'Cobblestone streets wind their way through a town steeped in history, each worn stone telling a tale of bygone eras. Ancient buildings with intricate facades stand as guardians of the past, while narrow alleyways invite exploration. The echoes of centuries-old footsteps resonate in the air, whispering stories of triumphs and tribulations. A visit to the town is a journey through time, as every corner reveals a piece of history waiting to be uncovered by those who walk its hallowed streets.',
    'In the heart of the bustling city, a vibrant market comes alive every weekend, showcasing an array of culinary delights. The air is infused with the aroma of exotic spices, freshly baked bread, and simmering stews. Street vendors offer a kaleidoscope of flavors, from spicy street tacos to fragrant bowls of noodle soup. The market is a mosaic of cultures, where locals and tourists alike embark on a gastronomic journey, savoring the rich tapestry of global cuisine that fills the air with tantalizing scents and promises of culinary adventure.',
    'In the heart of the countryside lies a tranquil meadow, where wildflowers sway in the soft breeze, painting the landscape with hues of violet, gold, and azure. The air is filled with the sweet melody of chirping birds, and the gentle rustle of leaves adds a rhythmic undertone. A meandering stream cuts through the meadow, providing a peaceful soundtrack to this idyllic scene. As the sun sets, casting a warm glow over the meadow, it becomes a haven for those seeking solace and connection with the untouched beauty of nature.'
]

In [171]:
from sklearn.feature_extraction.text import CountVectorizer

In [172]:
cv = CountVectorizer()

In [173]:
vectorized_corpus = cv.fit_transform(corpus)

In [174]:
vectorized_corpus = vectorized_corpus.toarray()

In [175]:
len(vectorized_corpus[0])

214

In [176]:
for (k, v) in cv.vocabulary_.items():
    print(k, v, vectorized_corpus[0][v])
    print(k, v, vectorized_corpus[1][v])
    print(k, v, vectorized_corpus[2][v])
    print(k, v, vectorized_corpus[3][v])
    

within 211 2
within 211 0
within 211 0
within 211 0
the 178 12
the 178 4
the 178 7
the 178 11
confines 40 1
confines 40 0
confines 40 0
confines 40 0
of 116 6
of 116 5
of 116 8
of 116 5
sunlit 168 1
sunlit 168 0
sunlit 168 0
sunlit 168 0
studio 166 2
studio 166 0
studio 166 0
studio 166 0
an 8 2
an 8 0
an 8 1
an 8 0
artist 13 3
artist 13 0
artist 13 0
artist 13 0
creative 45 1
creative 45 0
creative 45 0
creative 45 0
spirit 155 1
spirit 155 0
spirit 155 0
spirit 155 0
comes 39 1
comes 39 0
comes 39 1
comes 39 0
to 184 4
to 184 2
to 184 1
to 184 1
life 103 1
life 103 0
life 103 0
life 103 0
room 137 1
room 137 0
room 137 0
room 137 0
is 95 3
is 95 1
is 95 2
is 95 1
adorned 2 1
adorned 2 0
adorned 2 0
adorned 2 0
with 210 2
with 210 1
with 210 2
with 210 3
vibrant 196 1
vibrant 196 0
vibrant 196 1
vibrant 196 0
canvases 32 1
canvases 32 0
canvases 32 0
canvases 32 0
each 55 1
each 55 1
each 55 0
each 55 0
telling 175 1
telling 175 1
telling 175 0
telling 175 0
unique 193 1
unique 193 0


In [177]:
vectorized_corpus[2]

array([0, 0, 0, 1, 2, 1, 1, 0, 1, 0, 3, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 0, 0, 1, 0, 8, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 7, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0], dtype=int64)

In [178]:
s = cv.inverse_transform(vectorized_corpus[2:3,:])
len(s[0])

64

In [199]:
tokenizer = RegexpTokenizer('[a-zA-Z@.,0-9]+')
def myTokenizer(document):
    words = tokenizer.tokenize(document.lower())
    words = stopword_removal(words, stop_words)
    return words

In [200]:
myTokenizer(text)

['it', 'was', 'a', 'place', 'where', 'time', 'seemed', 'to', 'slow', 'hharshit8118@gmail.com', 'your', 'marks', 'are', '59.34', 'and', 'cost', 'is', '12,223', 'contact@sub1.sub2.example.org', 'h@.d', 'jane', 'doe@example.org', 'user123@example.net', 'mary', 'jane@example.co', 'info@sub.example.com', 'john.doe@example.com']


['place',
 'time',
 'seemed',
 'slow',
 'hharshit8118@gmail.com',
 'marks',
 '59.34',
 'cost',
 '12,223',
 'contact@sub1.sub2.example.org',
 'h@.d',
 'jane',
 'doe@example.org',
 'user123@example.net',
 'mary',
 'jane@example.co',
 'info@sub.example.com',
 'john.doe@example.com']

In [201]:
cv = CountVectorizer(tokenizer=myTokenizer)

In [202]:
vectorized_corpus = cv.fit_transform(corpus).toarray()
vectorized_corpus

['within', 'the', 'confines', 'of', 'a', 'sunlit', 'studio,', 'an', 'artist', 's', 'creative', 'spirit', 'comes', 'to', 'life.', 'the', 'room', 'is', 'adorned', 'with', 'vibrant', 'canvases,', 'each', 'telling', 'a', 'unique', 'story', 'born', 'from', 'the', 'depths', 'of', 'imagination.', 'brushes', 'dance', 'across', 'palettes,', 'blending', 'colors', 'with', 'purpose', 'and', 'passion.', 'the', 'scent', 'of', 'oil', 'paint', 'lingers', 'in', 'the', 'air,', 'a', 'testament', 'to', 'the', 'artist', 's', 'dedication', 'to', 'the', 'craft.', 'the', 'studio', 'is', 'a', 'sanctuary', 'where', 'ideas', 'flow', 'freely,', 'and', 'every', 'stroke', 'on', 'canvas', 'is', 'a', 'manifestation', 'of', 'an', 'inspired', 'journey,', 'inviting', 'observers', 'to', 'glimpse', 'into', 'the', 'soul', 'of', 'the', 'artist', 'and', 'the', 'world', 'that', 'unfolds', 'within', 'the', 'realm', 'of', 'creativity.']
['cobblestone', 'streets', 'wind', 'their', 'way', 'through', 'a', 'town', 'steeped', 'in', 

C:\Users\hhars\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


array([[1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
        1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,

In [203]:
len(vectorized_corpus[0])

191

In [204]:
s = cv.inverse_transform(vectorized_corpus)
s

[array(['across', 'adorned', 'air,', 'artist', 'blending', 'born',
        'brushes', 'canvas', 'canvases,', 'colors', 'comes', 'confines',
        'craft.', 'creative', 'creativity.', 'dance', 'dedication',
        'depths', 'every', 'flow', 'freely,', 'glimpse', 'ideas',
        'imagination.', 'inspired', 'inviting', 'journey,', 'life.',
        'lingers', 'manifestation', 'observers', 'oil', 'paint',
        'palettes,', 'passion.', 'purpose', 'realm', 'room', 'sanctuary',
        'scent', 'soul', 'spirit', 'story', 'stroke', 'studio', 'studio,',
        'sunlit', 'telling', 'testament', 'unfolds', 'unique', 'vibrant',
        'within', 'world'], dtype='<U13'),
 array(['air,', 'alleyways', 'ancient', 'buildings', 'bygone', 'centuries',
        'cobblestone', 'corner', 'echoes', 'eras.', 'every',
        'exploration.', 'facades', 'footsteps', 'guardians', 'hallowed',
        'history', 'history,', 'intricate', 'invite', 'journey', 'narrow',
        'old', 'past,', 'piece', 'resonat

In [209]:
test_corpus = ['I love cricket untouched vibrant']

In [210]:
cv.transform(test_corpus).toarray()

['i', 'love', 'cricket', 'untouched', 'vibrant']


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [211]:
sent1 = "this is good movie"
sent2 = "this is not good movie"
sent3 = "this is good movie but actor was not good"

In [217]:
doc = [sent1, sent2, sent3]
cv = CountVectorizer(ngram_range=(1,1))
vectorized_corpus = cv.fit_transform(doc).toarray()
print(vectorized_corpus)
cv.vocabulary_

[[0 0 1 1 1 0 1 0]
 [0 0 1 1 1 1 1 0]
 [1 1 2 1 1 1 1 1]]


{'this': 6,
 'is': 3,
 'good': 2,
 'movie': 4,
 'not': 5,
 'but': 1,
 'actor': 0,
 'was': 7}

In [218]:
cv = CountVectorizer(ngram_range=(2,2))
vectorized_corpus = cv.fit_transform(doc).toarray()
print(vectorized_corpus)
cv.vocabulary_

[[0 0 1 1 0 0 0 1 0]
 [0 0 1 0 1 0 1 1 0]
 [1 1 1 1 0 1 1 1 1]]


{'this is': 7,
 'is good': 3,
 'good movie': 2,
 'is not': 4,
 'not good': 6,
 'movie but': 5,
 'but actor': 1,
 'actor was': 0,
 'was not': 8}

In [223]:
cv = CountVectorizer(ngram_range=(1,3), tokenizer=myTokenizer)
vectorized_corpus = cv.fit_transform(doc).toarray()
print(vectorized_corpus)
cv.vocabulary_

['this', 'is', 'good', 'movie']
['this', 'is', 'not', 'good', 'movie']
['this', 'is', 'good', 'movie', 'but', 'actor', 'was', 'not', 'good']
[[0 0 0 1 1 0 1 0 0 0 0 0]
 [0 0 0 1 1 0 1 0 0 1 1 1]
 [1 1 1 2 1 1 1 1 1 1 1 0]]


C:\Users\hhars\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\feature_extraction\text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


{'good': 3,
 'movie': 6,
 'good movie': 4,
 'not': 9,
 'not good': 10,
 'not good movie': 11,
 'actor': 0,
 'movie actor': 7,
 'actor not': 1,
 'good movie actor': 5,
 'movie actor not': 8,
 'actor not good': 2}

In [224]:
cv.inverse_transform(vectorized_corpus)

[array(['good', 'good movie', 'movie'], dtype='<U16'),
 array(['good', 'good movie', 'movie', 'not', 'not good', 'not good movie'],
       dtype='<U16'),
 array(['actor', 'actor not', 'actor not good', 'good', 'good movie',
        'good movie actor', 'movie', 'movie actor', 'movie actor not',
        'not', 'not good'], dtype='<U16')]