In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('Train/Train.csv')

In [3]:
df.head()

feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [4]:
data = df.values
X = data[:, :-1]
Y = data[:, -1].reshape((-1,1))
print(X, Y)

[[ 0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [-0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [-1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [-1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]] [[ -82.15466656]
 [ -48.89796018]
 [  77.2703707 ]
 ...
 [-107.51050797]
 [ -47.34155781]
 [-115.93900296]]


In [5]:
m = X.shape[0]
m

1600

In [6]:
ones = np.ones((m, 1))
X = np.hstack((ones, X))
print(X)

[[ 1.          0.29341624 -0.94559871 -0.42110515  0.40681602  0.52566183]
 [ 1.         -0.83608408 -0.18922804 -0.77640262 -1.05383124  0.59799685]
 [ 1.          0.23642511  0.13283602 -0.14772298  0.69985396 -0.18736416]
 ...
 [ 1.          1.04417694 -0.89920649  1.73039905 -1.87105676  0.44251965]
 [ 1.         -1.2691729  -0.00505216  1.85766873 -1.08036482  0.73633394]
 [ 1.         -1.88400025 -0.84942743 -1.45227035  0.48861308  1.4595758 ]]


In [7]:
def hypothesis(X, theta):
    Y_ = np.dot(X, theta)
    return Y_

In [8]:
def error(X, Y, theta):
    Y_ = hypothesis(X, theta)
    te = np.sum((Y_ - Y) ** 2)
    return te / m

In [9]:
def gradient(X, Y, theta):
    ypred = hypothesis(X, theta)
    grad = np.dot(X.T, (ypred - Y))
    return grad / m

In [10]:
def gradientDescent(X, Y, alpha = 0.1, iters = 200):
    n = X.shape[1]
    theta = np.zeros((n, 1))
    el = []
    for i in range(iters):
        grad = gradient(X, Y, theta)
        e = error(X, Y, theta)
        el.append(e)
        theta = theta - alpha * grad
    return theta, el

In [11]:
theta, el = gradientDescent(X, Y)
# print(theta)
# print(el)

In [12]:
Y_ = hypothesis(X, theta)
print(Y_)

[[ -57.87196322]
 [ -89.46019547]
 [  53.95305923]
 ...
 [-115.65802571]
 [ -64.27649724]
 [-116.11442886]]


In [13]:
num = (Y_ - Y) ** 2
den = (Y - np.mean(Y)) ** 2
rsq = (1 - (np.sum(num) / np.sum(den))) * 100
print(rsq)

96.60939669975616


In [14]:
testx = pd.read_csv('Test/Test.csv')
testx = testx.values

In [15]:
x0 = np.ones((testx.shape[0], 1))
x0.shape
testx = np.concatenate((testx, x0), axis=1)
testx.shape

(400, 6)

In [35]:
Ypred = hypothesis(testx, theta)
# print(Ypred)

In [36]:
ones = np.arange(400).reshape((400, 1)).astype(np.int32)
ones
Ypred = np.concatenate((ones, Ypred), axis=1)
Ypred

array([[   0.        ,  -19.39463076],
       [   1.        ,   76.93156107],
       [   2.        ,   -6.84555376],
       [   3.        ,   -1.89052065],
       [   4.        ,  115.64629431],
       [   5.        ,  208.52445913],
       [   6.        ,  -31.16707992],
       [   7.        ,  -59.33480119],
       [   8.        ,  145.75006575],
       [   9.        ,  -14.20589979],
       [  10.        ,   20.94919486],
       [  11.        ,  -47.01820077],
       [  12.        ,  -70.60700119],
       [  13.        ,  177.35044328],
       [  14.        ,   65.7311515 ],
       [  15.        ,   -3.12816902],
       [  16.        ,   41.94461578],
       [  17.        ,   -9.58366668],
       [  18.        ,    9.6205703 ],
       [  19.        ,  161.32190164],
       [  20.        ,  -31.93054986],
       [  21.        ,  -28.04660981],
       [  22.        ,   38.2567898 ],
       [  23.        ,  202.53487773],
       [  24.        , -156.70255471],
       [  25.        , -1

In [32]:
Ypred[:, 0].astype(np.int32)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [33]:
df = pd.DataFrame(Ypred, columns=["Id", "target"])
df.head()

Id      target
0  0.0  -19.394631
1  1.0   76.931561
2  2.0   -6.845554
3  3.0   -1.890521
4  4.0  115.646294

In [19]:
df.to_csv('Test/PredictedY.csv', index=False)

In [20]:
df = pd.read_csv("Test/PredictedY.csv")
df.head()

Id      target
0  0.0  -19.394631
1  1.0   76.931561
2  2.0   -6.845554
3  3.0   -1.890521
4  4.0  115.646294